apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: orderflow
  name: orderflow-kafka-data
  labels:
    part-of: orderflow
    component: messaging
    name: kafka
    instance: orderflow-kafka
    version: "7.8.0"
    managed-by: kubectl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path