apiVersion: v1
kind: Service
metadata:
  namespace: orderflow
  name: kafka
  labels:
    part-of: orderflow
    component: messaging
    name: kafka
    instance: orderflow-kafka
    version: "7.8.0"
    managed-by: kubectl
spec:
  selector:
    part-of: orderflow
    component: messaging
    name: kafka
    instance: orderflow-kafka
  ports:
    - port: 9092
      targetPort: external
      name: external
    - port: 29092
      targetPort: internal
      name: internal
  type: ClusterIP