apiVersion: v1
kind: Service
metadata:
  namespace: orderflow
  name: postgres
  labels:
    part-of: orderflow
    component: database
    name: postgres
    instance: orderflow-postgres
    version: "15"
    managed-by: kubectl
spec:
  selector:
    part-of: orderflow
    component: database
    name: postgres
    instance: orderflow-postgres
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
  type: ClusterIP