apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: orderflow
  name: orderflow-redis
  labels:
    part-of: orderflow
    component: cache
    name: redis
    instance: orderflow-redis
    version: "7"
    managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      part-of: orderflow
      component: cache
      name: redis
      instance: orderflow-redis
  template:
    metadata:
      labels:
        part-of: orderflow
        component: cache
        name: redis
        instance: orderflow-redis
        version: "7"
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          startupProbe:
            exec:
              command:
                - redis-cli
                - ping
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"