  {{- if .Values.eurekaServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: {{ .Values.namespace }}
  labels:
    app: eureka-server
    component: discovery
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWaves.discovery }}"
spec:
  type: ClusterIP
  selector:
    app: eureka-server
  ports:
    - name: eureka
      port: {{ .Values.eurekaServer.port }}
      targetPort: {{ .Values.eurekaServer.port }}
      protocol: TCP
        {{- end }}