spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.example.user: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE