spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: orderflow
    password: orderflow123

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  admin:
    emails:
      - duddnddnfl@naver.com
      - admin@orderflow.com

jwt:
  secret: ${JWT_SECRET}
  expiration:
    accessToken: 3600000
    refreshToken: 604800000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.example.user: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE