apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-logging-service
  namespace: orderflow
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-logging-service
  template:
    metadata:
      labels:
        app: event-logging-service
    spec:
      containers:
        - name: event-logging-service
          image: jimineutron/orderflow-event-logging-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: orderflow-config
            - secretRef:
                name: orderflow-secrets
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx384m"
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
            limits:
              memory: "768Mi"
              cpu: "800m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: event-logging-service
  namespace: orderflow
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  selector:
    app: event-logging-service
  ports:
    - port: 8088
      targetPort: 8088
  type: ClusterIP