global:
  postgresql:
    auth:
      postgresPassword: "orderflow123"
      username: "orderflow"
      password: "orderflow123"
      database: "orderflow"

primary:
  persistence:
    enabled: true
    size: 5Gi
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  initdb:
    scriptsConfigMap: postgresql-init-scripts

metrics:
  enabled: false
