{{- if .Values.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ include "orderflow.namespace" . }}
  labels:
    {{- include "orderflow.labels" . | nindent 4 }}
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ include "orderflow.namespace" . }}
  labels:
    {{- include "orderflow.labels" . | nindent 4 }}
    app: redis
spec:
  serviceName: redis
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 6379
              name: redis
          {{- if .Values.secrets.redisPassword }}
          args:
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orderflow-secrets
                  key: REDIS_PASSWORD
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.redis.resources.requests.memory }}
              cpu: {{ .Values.redis.resources.requests.cpu }}
            limits:
              memory: {{ .Values.redis.resources.limits.memory }}
              cpu: {{ .Values.redis.resources.limits.cpu }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ include "orderflow.namespace" . }}
  labels:
    {{- include "orderflow.labels" . | nindent 4 }}
    app: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      {{- if eq .Values.redis.service.type "NodePort" }}
      nodePort: {{ .Values.redis.service.nodePort }}
      {{- end }}
      name: redis
  selector:
    app: redis
{{- end }}