apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: orderflow
  namespace: argocd
spec:
  description: OrderFlow E-commerce Project
  sourceRepos:
    - 'https://github.com/JoJimi/OrderFlow'
  destinations:
    - namespace: orderflow
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orderflow-infra
  namespace: argocd
spec:
  project: orderflow
  source:
    repoURL: https://github.com/JoJimi/OrderFlow
    targetRevision: develop
    path: k8s/infra
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: orderflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true