apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: orderflow
  name: orderflow-api-gateway
  labels:
    part-of: orderflow
    component: gateway
    name: api-gateway
    instance: orderflow-api-gateway
    version: "1.0.0"
    managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      part-of: orderflow
      component: gateway
      name: api-gateway
      instance: orderflow-api-gateway
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        part-of: orderflow
        component: gateway
        name: api-gateway
        instance: orderflow-api-gateway
        version: "1.0.0"
    spec:
      containers:
        - name: api-gateway
          image: jimineutron/orderflow-api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: orderflow-config
            - secretRef:
                name: orderflow-secret
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
            failureThreshold: 36
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              memory: "384Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"