apiVersion: v1
kind: Service
metadata:
  namespace: orderflow
  name: api-gateway
  labels:
    part-of: orderflow
    component: gateway
    name: api-gateway
    instance: orderflow-api-gateway
    version: "1.0.0"
    managed-by: kubectl
spec:
  selector:
    part-of: orderflow
    component: gateway
    name: api-gateway
    instance: orderflow-api-gateway
  ports:
    - port: 8080
      targetPort: http
      nodePort: 30080
      name: http
  type: NodePort