apiVersion: v1
kind: ConfigMap
metadata:
  name: orderflow-config
  namespace: orderflow
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_HOST: "postgresql"
  DB_PORT: "5432"
  DB_POOL_SIZE: "10"
  DB_MIN_IDLE: "2"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
  FRONT_BASE_URL: "http://localhost:3000"