apiVersion: v1
kind: Service
metadata:
  namespace: orderflow
  name: eureka-server
  labels:
    part-of: orderflow
    component: discovery
    name: eureka-server
    instance: orderflow-eureka-server
    version: "1.0.0"
    managed-by: kubectl
spec:
  selector:
    part-of: orderflow
    component: discovery
    name: eureka-server
    instance: orderflow-eureka-server
  ports:
    - port: 8761
      targetPort: http
      name: http
  type: ClusterIP