apiVersion: v1
kind: Service
metadata:
  namespace: orderflow
  name: payment-service
  labels:
    part-of: orderflow
    component: backend-server
    name: payment-service
    instance: orderflow-payment-service
    version: "1.0.0"
    managed-by: kubectl
spec:
  selector:
    part-of: orderflow
    component: backend-server
    name: payment-service
    instance: orderflow-payment-service
  ports:
    - port: 8084
      targetPort: http
      name: http
  type: ClusterIP