apiVersion: v1
kind: Service
metadata:
  namespace: orderflow
  name: user-service
  labels:
    part-of: orderflow
    component: backend-server
    name: user-service
    instance: orderflow-user-service
    version: "1.0.0"
    managed-by: kubectl
spec:
  selector:
    part-of: orderflow
    component: backend-server
    name: user-service
    instance: orderflow-user-service
  ports:
    - port: 8081
      targetPort: http
      name: http
  type: ClusterIP