apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: orderflow
  name: orderflow-user-service
  labels:
    part-of: orderflow
    component: backend-server
    name: user-service
    instance: orderflow-user-service
    version: "1.0.0"
    managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      part-of: orderflow
      component: backend-server
      name: user-service
      instance: orderflow-user-service
  template:
    metadata:
      labels:
        part-of: orderflow
        component: backend-server
        name: user-service
        instance: orderflow-user-service
        version: "1.0.0"
    spec:
      containers:
        - name: user-service
          image: jimineutron/orderflow-user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
          envFrom:
            - configMapRef:
                name: orderflow-config
            - secretRef:
                name: orderflow-secret
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 5
            failureThreshold: 36
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              memory: "384Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"